name: Index

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build main
        if: github.ref == 'refs/heads/main'
        uses: dicky2ux/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo branch=main /var/repo/thrive.git/hooks/post-receive

      - name: Build develop
        if: github.ref == 'refs/heads/develop'
        uses: dicky2ux/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo branch=develop /var/repo/thrive.git/hooks/post-receive
